# Generated by Django 4.1 on 2022-10-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('lastname', models.CharField(blank=True, max_length=200, verbose_name='lastname')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=12, verbose_name='Phone')),
                ('message', models.TextField(blank=True, max_length=300, verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='mywork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_info', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_heading', models.CharField(blank=True, max_length=100, null=True)),
                ('resume', models.FileField(blank=True, upload_to='resume_mayank')),
            ],
        ),
        migrations.CreateModel(
            name='TechSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.URLField(blank=True, null=True)),
                ('skill_desc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
