# Generated by Django 4.1 on 2022-10-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_socialicons'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialicons',
            name='icon_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
