# Generated by Django 4.1 on 2022-10-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_techskills_skill_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='refrences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refrences_info', models.TextField(blank=True, max_length=100, null=True)),
                ('refrences_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
