# Generated by Django 4.1 on 2022-10-15 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_refrences_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mywork',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='techskills',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
