# Generated by Django 4.1 on 2022-10-16 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_techskills_skill_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techskills',
            name='skill_name',
        ),
    ]
