# Generated by Django 4.1 on 2022-10-17 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_techskills_skill_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='carosuel_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carosuel_heading', models.CharField(blank=True, max_length=50, null=True)),
                ('carosuel_para', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='carosol_img')),
                ('carosuel_date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
