# Generated by Django 4.1 on 2022-10-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_carosuel_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carosuel_info',
            name='carosuel_heading',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
